name: spaarma
channels:
  - pyg
  - pytorch
  - conda-forge
dependencies:
  - python=3.10
  - pytorch>=2.0
  - pyg>=2.3
  - numpy>=1.23
  - scipy>=1.9
  - scikit-learn>=1.2
  - anndata>=0.9
  - scanpy>=1.9
  - pandas>=1.5
  - matplotlib>=3.6
  - jupyterlab>=4
  - scikit-misc>=0.2
  - louvain>=0.8
  - leidenalg>=0.10
  - python-igraph>=0.10
  - r-base>=4.2
  - r-mclust
  - rpy2>=3.5
  - pip
  - pip:
      - -e .
